development:
  adapter: postgresql
  encoding: utf8
  database: simpletask_development
  pool: 5
  username: tosha

test:
  adapter: postgresql
  encoding: utf8
  database: simpletask_test
  pool: 5
  username: tosha

production:
  adapter: postgresql
  encoding: utf8
  database: simpletask_production
  pool: 5
  username: postgres
